#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'

class GetResult
  include ::Thrift::Struct
  ::Thrift::Struct.field_accessor self, :context, :results
  FIELDS = {
    1 => {:type => ::Thrift::Types::STRING, :name => 'context'},
    2 => {:type => ::Thrift::Types::LIST, :name => 'results', :element => {:type => ::Thrift::Types::STRING}}
  }
end

class FailureException < StandardError
  include ::Thrift::Struct
  def initialize(message=nil)
    super()
    self.message = message
  end

  ::Thrift::Struct.field_accessor self, :message
  FIELDS = {
    1 => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }
end

